const ipsum = () => `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ullamcorper nisl laoreet, eleifend ipsum ut, vulputate felis. Aenean laoreet feugiat mauris, eget sodales eros lacinia at. Mauris egestas quam sed sapien venenatis porta. Phasellus semper, dolor vel luctus consectetur, risus velit aliquam dolor, ac interdum nisl tortor et mi. Praesent dapibus euismod nulla sed eleifend. Nam quis tincidunt elit. Duis neque tortor, varius in velit non, aliquet lobortis libero. Maecenas sit amet diam viverra, rhoncus metus blandit, sollicitudin lacus. Ut et augue aliquam, scelerisque augue sed, porttitor velit. Phasellus a leo imperdiet, efficitur ante et, porta magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ligula mauris, ornare ac convallis at, sagittis eget enim. Ut commodo mattis nulla, eu fermentum neque pellentesque in. Sed condimentum tortor nibh, id dapibus neque tempus ac. In hac habitasse platea dictumst. Suspendisse pulvinar elit tortor, a pellentesque ligula efficitur at.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor, purus vitae viverra molestie, quam lorem fermentum elit, ac mollis felis enim bibendum magna. Praesent elementum ut lacus vel suscipit. Maecenas augue diam, aliquam a dapibus sit amet, porttitor ut sapien. Nulla facilisi. Fusce et dignissim tortor. Integer et tincidunt tellus. Fusce tempus augue ac consequat ultricies. Nullam tincidunt ex quis ante semper varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ut orci at felis hendrerit vestibulum.

Proin in erat felis. Mauris vitae ornare justo, a blandit urna. Proin tempor enim at magna efficitur, ac semper odio blandit. Proin eu massa commodo, varius velit eu, tristique velit. Fusce id lorem efficitur, eleifend elit vitae, pharetra turpis. Curabitur finibus nisl quis augue ullamcorper facilisis. Aliquam auctor, sapien ac posuere accumsan, augue massa efficitur ligula, ac egestas turpis turpis sit amet purus. Morbi purus sapien, gravida sit amet magna quis, consectetur ultrices leo. Maecenas consequat tellus auctor ligula mattis viverra a vel turpis. Nulla augue neque, dignissim id nulla nec, aliquet mattis nunc. Integer in nulla semper, congue ante ut, tincidunt risus. Donec facilisis odio urna, at rhoncus lorem ornare at. Donec ullamcorper urna lorem, vitae tempor quam tempor eget.

Maecenas lorem ex, imperdiet dictum bibendum in, rutrum eget quam. In euismod consequat metus et scelerisque. Morbi tempor lectus vel semper dignissim. Maecenas aliquet, turpis in ultrices tincidunt, ante purus lobortis velit, sit amet condimentum lacus augue sed ante. Praesent pulvinar, ligula et vulputate feugiat, urna dolor vestibulum orci, iaculis porta ante lorem eu lorem. Duis ac maximus purus, et pulvinar sapien. Integer dictum scelerisque efficitur. Aliquam erat volutpat. Nulla facilisi. Sed a velit dapibus, commodo mauris a, feugiat ex.

Pellentesque a fringilla odio, sed vestibulum leo. In vitae dolor eu sapien scelerisque egestas. Morbi non dolor et massa porttitor luctus eu quis ante. Curabitur efficitur hendrerit orci vel placerat. Nullam accumsan odio vitae iaculis convallis. Aliquam leo leo, ullamcorper sit amet nisl in, porta molestie sapien. Nunc id faucibus sapien. Fusce faucibus vestibulum nisi sed luctus. Cras finibus lectus eget tellus mattis scelerisque. Suspendisse quis fermentum tortor.`;

export default ipsum;
